## 2021.3.29单目相机参数重新标定
## 相机参数
fx: 320
fy: 320
x0: 320
y0: 240

## 畸变参数
k1: 0.0
k2: 0.0
p1: 0.0
p2: 0.0
k3: 0.0

## aruco_det 二维码的边长(默认0.2m)  单二维码检测aruco_det.cpp暂不用这个，是在aruco_det.launch里设置二维码边长
aruco_det_len: 0.188

## ellipse_det 圆的半径(默认0.2m)
ellipse_det_r: 0.6

## kcf_tracker 目标高度(默认1.7m)
kcf_tracker_h: 1.7

## landpad_det 降落板边长(默认0.6m)，0.6m包括边缘白色部分，黑色部分边长为0.4m
## 2021.1.18降落板边长为0.188m
#landpad_det_len: 0.188
#A4纸打印，是21厘米
#landpad_det_len: 0.21
#landpad_det_len: 0.285

#一大一小中心重叠的二维码降落板，其中最大的二维码的边长，单位米，默认0.19米(A4纸打印)   multi_aruco_det.cpp使用
multi_aruco_max_aruco_len: 0.19

## digitnum_det 数字周围的方框边长(默认1m)
digitnum_det_len: 0.162

## YOLO检测中的行人高度(m)
yolo_det_person_height: 1.7

## YOLO检测中的无人机宽度(m)
yolo_det_uav_width: 0.5

